# Generated by Django 5.2.6 on 2025-09-08 07:25

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0003_alter_todolist_done_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phonenumber',
            field=models.CharField(default=1, max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqam +998 bilan boshlanishi va jami 13 ta belgidan iborat boâ€˜lishi kerak. Masalan: +998901234567', regex='^\\+998\\d{9}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='sms_kod',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
